// @ts-nocheck

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Product listing
  productSidebar: [
    // {type: 'autogenerated', dirName: '.'},
    {
      type: "doc",
      id: "ESP32/main",
      label: "Support & Warranty",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "ESP32/products-intro",
      label: "ESP32",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "ESP32 Basic Tutorials",
      href: "/ESP32-Tutorials-Intro",
    },
    {
      type: "link",
      label: "ESP32-S3 Boards",
      href: "/ESP32-S3",
    },
    {
      type: "link",
      label: "ESP32-P4 Boards",
      href: "/ESP32-P4",
    },
    {
      type: "link",
      label: "ESP32-C3 Boards",
      href: "/ESP32-C3",
    },
    {
      type: "link",
      label: "ESP32-C6 Boards",
      href: "/ESP32-C6",
    },
    {
      type: "doc",
      id: "Raspberry-Pi-Pico/products-intro",
      label: "Raspberry Pi Pico",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "Raspberry Pi Pico Basic Tutorials",
      href: "/Raspberry-Pi-Pico-Tutorials-Intro",
    },
    {
      type: "link",
      label: "RP2350 Boards",
      href: "/RP2350",
    },
    {
      type: "doc",
      id: "IoT-Communication/products-intro",
      label: "IoT / Communication",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "Long Range Wireless",
      href: "/Long-Range-Wireless",
    },
    {
      type: "doc",
      id: "Displays/Displays-Overview",
      label: "Displays",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "LCD Displays",
      href: "/LCD",
    },
    {
      type: "doc",
      id: "Others/main",
      label: "Misc Modules",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "Camera / Audio / Video",
      href: "/Camera-Audio-Video",
    },
  ],

  // ESP32
  // ESP32 - Basic Tutorials
  esp32TutorialSidebar: [
    {
      type: "doc",
      id: "ESP32/Tutorials/ESP32-Tutorials-Intro",
      label: "ESP32 Basic Tutorials",
    },
    {
      type: "doc",
      id: "ESP32/Tutorials/Getting-To-Know-Esp32",
      label: "Getting to Know the ESP32",
    },
    {
      type: "category",
      label: "Arduino Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/Arduino-Tutorials/Arduino-Tutorial-Introduction",
      },
      items: [
        "ESP32/Tutorials/Arduino-Tutorials/1",
        "ESP32/Tutorials/Arduino-Tutorials/2",
        "ESP32/Tutorials/Arduino-Tutorials/3",
        "ESP32/Tutorials/Arduino-Tutorials/4",
        "ESP32/Tutorials/Arduino-Tutorials/5",
        "ESP32/Tutorials/Arduino-Tutorials/6",
        "ESP32/Tutorials/Arduino-Tutorials/7",
        "ESP32/Tutorials/Arduino-Tutorials/8",
        "ESP32/Tutorials/Arduino-Tutorials/9",
        "ESP32/Tutorials/Arduino-Tutorials/10",
        "ESP32/Tutorials/Arduino-Tutorials/11",
        "ESP32/Tutorials/Arduino-Tutorials/12",
        {
          type: "category",
          label: "Section 13 Comprehensive Projects",
          link: { type: "doc", id: "ESP32/Tutorials/Arduino-Tutorials/13" },
          items: [
            "ESP32/Tutorials/Arduino-Tutorials/13-1",
            "ESP32/Tutorials/Arduino-Tutorials/13-2",
            "ESP32/Tutorials/Arduino-Tutorials/13-3",
            "ESP32/Tutorials/Arduino-Tutorials/13-4",
            "ESP32/Tutorials/Arduino-Tutorials/13-5",
            "ESP32/Tutorials/Arduino-Tutorials/13-6",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "ESP-IDF Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/ESP-IDF-Tutorials/ESP32-ESP-IDF-Tutorial-Introduction",
      },
      items: [
        "ESP32/Tutorials/ESP-IDF-Tutorials/1",
        "ESP32/Tutorials/ESP-IDF-Tutorials/2",
        "ESP32/Tutorials/ESP-IDF-Tutorials/3",
        "ESP32/Tutorials/ESP-IDF-Tutorials/4",
        "ESP32/Tutorials/ESP-IDF-Tutorials/5",
        "ESP32/Tutorials/ESP-IDF-Tutorials/6",
        {
          type: "category",
          label: "Section 7 Peripheral",
          link: { type: "doc", id: "ESP32/Tutorials/ESP-IDF-Tutorials/7" },
          items: [
            "ESP32/Tutorials/ESP-IDF-Tutorials/7-1",
            "ESP32/Tutorials/ESP-IDF-Tutorials/7-2",
            "ESP32/Tutorials/ESP-IDF-Tutorials/7-3",
          ],
        },
        "ESP32/Tutorials/ESP-IDF-Tutorials/8",
        "ESP32/Tutorials/ESP-IDF-Tutorials/9",
      ],
    },
    {
      type: "category",
      label: "MicroPython Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/MicroPython-Tutorials/ESP32-MicroPython-Tutorial-Introduction",
      },
      items: [
        "ESP32/Tutorials/MicroPython-Tutorials/1",
        "ESP32/Tutorials/MicroPython-Tutorials/2",
        "ESP32/Tutorials/MicroPython-Tutorials/3",
        "ESP32/Tutorials/MicroPython-Tutorials/4",
        "ESP32/Tutorials/MicroPython-Tutorials/5",
        "ESP32/Tutorials/MicroPython-Tutorials/6",
        "ESP32/Tutorials/MicroPython-Tutorials/7",
        "ESP32/Tutorials/MicroPython-Tutorials/8",
        "ESP32/Tutorials/MicroPython-Tutorials/9",
        "ESP32/Tutorials/MicroPython-Tutorials/10",
        "ESP32/Tutorials/MicroPython-Tutorials/11",
        {
          type: "category",
          label: "Section 12 Comprehensive Projects",
          link: { type: "doc", id: "ESP32/Tutorials/MicroPython-Tutorials/12" },
          items: [
            "ESP32/Tutorials/MicroPython-Tutorials/12-1",
            "ESP32/Tutorials/MicroPython-Tutorials/12-2",
            "ESP32/Tutorials/MicroPython-Tutorials/12-3",
            "ESP32/Tutorials/MicroPython-Tutorials/12-4",
            "ESP32/Tutorials/MicroPython-Tutorials/12-5",
            "ESP32/Tutorials/MicroPython-Tutorials/12-6",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "AI Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/AI-Tutorials/AI-Tutorial-Introduction",
      },
      items: ["ESP32/Tutorials/AI-Tutorials/1"],
    },
  ],
  // ESP32 - individual models
  esp32s3Sidebar: [
    {
      type: "doc",
      id: "ESP32/ESP32-S3-Overview",
      label: "ESP32-S3",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "ESP32/ESP32-S3" },
  ],
  esp32p4Sidebar: [
    {
      type: "doc",
      id: "ESP32/ESP32-P4-Overview",
      label: "ESP32-P4",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "ESP32/ESP32-P4" },
  ],
  esp32c3Sidebar: [
    {
      type: "doc",
      id: "ESP32/ESP32-C3-Overview",
      label: "ESP32-C3",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "ESP32/ESP32-C3" },
  ],
  esp32c6Sidebar: [
    {
      type: "doc",
      id: "ESP32/ESP32-C6-Overview",
      label: "ESP32-C6",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "ESP32/ESP32-C6" },
  ],

  // Raspberry Pi Pico
  // Raspberry Pi Pico - Basic Tutorials
  raspberrypipicoTutorialSidebar: [
    {
      type: "doc",
      id: "Raspberry-Pi-Pico/Tutorials/Raspberry-Pi-Pico-Tutorials-Intro",
      label: "Raspberry Pi Pico Basic Tutorials",
    },
    {
      type: "doc",
      id: "Raspberry-Pi-Pico/Tutorials/Getting-To-Know-Raspberry-Pi-Pico",
      label: "Getting to Know the Raspberry Pi Pico",
    },
    {
      type: "category",
      label: "MicroPython Basic Tutorial",
      link: {
        type: "doc",
        id: "Raspberry-Pi-Pico/Tutorials/MicroPython-Tutorials/Raspberry-Pi-Pico-MicroPython-Tutorial-Introduction",
      },
      items: [],
    },
    {
      type: "category",
      label: "C/C++ Basic Tutorial",
      link: {
        type: "doc",
        id: "Raspberry-Pi-Pico/Tutorials/C-Tutorials/Raspberry-Pi-Pico-C-Tutorial-Introduction",
      },
      items: [],
    },
    {
      type: "category",
      label: "Arduino Basic Tutorial",
      link: {
        type: "doc",
        id: "Raspberry-Pi-Pico/Tutorials/Arduino-Tutorials/Arduino-Tutorial-Introduction",
      },
      items: [],
    },
  ],
  // Raspberry Pi Pico - RP2350 series
  rp2350Sidebar: [
    {
      type: "doc",
      id: "Raspberry-Pi-Pico/RP2350-Overview",
      label: "RP2350",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "Raspberry-Pi-Pico/RP2350" },
  ],

  // IoT / Communication
  // IoT / Communication - Long Range Wireless
  longRangeWirelessSidebar: [
    {
      type: "doc",
      id: "IoT-Communication/Long-Range-Wireless/products-intro",
      label: "Long Range Wireless",
      className: "sidebar-title",
    },

    {
      type: "doc",
      id: "IoT-Communication/Long-Range-Wireless/5G-4G-GSM-GPRS-Intro",
      label: "5G/4G/GSM/GPRS",
      className: "sidebar-title",
    },
    {
      type: "autogenerated",
      dirName: "IoT-Communication/Long-Range-Wireless/5G-4G-GSM-GPRS",
    },

    {
      type: "doc",
      id: "IoT-Communication/Long-Range-Wireless/GNSS-GPS-Intro",
      label: "GNSS/GPS",
      className: "sidebar-title",
    },
    {
      type: "autogenerated",
      dirName: "IoT-Communication/Long-Range-Wireless/GNSS-GPS",
    },
  ],

  // Displays
  // Displays - LCD
  lcdSidebar: [
    {
      type: "doc",
      id: "Displays/LCD/LCD-Overview",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "Displays/LCD/5-27p5-Overview",
      label: "5 - 27 inch",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "Displays/LCD/5-27p5" },
  ],

  // Misc Modules
  // Misc Modules - Camera / Audio / Video
  cameraAudioVideoSidebar: [
    {
      type: "doc",
      id: "Others/Camera-Audio-Video/Camera-Overview",
      label: "Camera / Audio / Video",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "Others/Camera-Audio-Video/USB-Camera-Overview",
      label: "USB Camera",
      className: "sidebar-title",
    },
    { type: "autogenerated", dirName: "Others/Camera-Audio-Video/USB-Camera" },
    {
      type: "doc",
      id: "Others/Camera-Audio-Video/GMSL-Deser-Board-Overview",
      label: "GMSL Deser Board",
      className: "sidebar-title",
    },
    {
      type: "autogenerated",
      dirName: "Others/Camera-Audio-Video/GMSL-Deser-Board",
    },
  ],
};

export default sidebars;
