// @ts-nocheck

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  esp32Sidebar: [
    // {type: 'autogenerated', dirName: '.'},
    {
      type: "doc",
      id: "ESP32/main",
      label: "Support & Warranty",
      className: "sidebar-title",
    },
    {
      type: "doc",
      id: "ESP32/products-intro",
      label: "ESP32",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "ESP32 Basic Tutorials",
      href: "/ESP32-Tutorials-Intro",
    },
    {
      type: "link",
      label: "ESP32-S3 Boards",
      href: "/ESP32-S3",
    },
    {
      type: "link",
      label: "ESP32-P4 Boards",
      href: "/ESP32-P4",
    },
    {
      type: "link",
      label: "ESP32-C3 Boards",
      href: "/ESP32-C3",
    },
    {
      type: "link",
      label: "ESP32-C6 Boards",
      href: "/ESP32-C6",
    },
    {
      type: "doc",
      id: "GMSL/main",
      label: "GMSL",
      className: "sidebar-title",
    },
    {
      type: "link",
      label: "GMSL Deser Board",
      href: "/GMSL/GMSL-Deser-Board",
    },
  ],
  esp32TutorialSidebar: [
    {
      type: "doc",
      id: "ESP32/Tutorials/ESP32-Tutorials-Intro",
      label: "ESP32 Basic Tutorials",
    },
    {
      type: "doc",
      id: "ESP32/Tutorials/Getting-To-Know-Esp32",
      label: "Getting to Know the ESP32",
    },
    {
      type: "category",
      label: "Arduino Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/Arduino-Tutorials/Arduino-Tutorial-Introduction",
      },
      items: [
        "ESP32/Tutorials/Arduino-Tutorials/1",
        "ESP32/Tutorials/Arduino-Tutorials/2",
        "ESP32/Tutorials/Arduino-Tutorials/3",
        "ESP32/Tutorials/Arduino-Tutorials/4",
        "ESP32/Tutorials/Arduino-Tutorials/5",
        "ESP32/Tutorials/Arduino-Tutorials/6",
        "ESP32/Tutorials/Arduino-Tutorials/7",
        "ESP32/Tutorials/Arduino-Tutorials/8",
        "ESP32/Tutorials/Arduino-Tutorials/9",
        "ESP32/Tutorials/Arduino-Tutorials/10",
        "ESP32/Tutorials/Arduino-Tutorials/11",
        "ESP32/Tutorials/Arduino-Tutorials/12",
        {
          type: "category",
          label: "Section 13 Comprehensive Projects",
          link: { type: "doc", id: "ESP32/Tutorials/Arduino-Tutorials/13" },
          items: [
            "ESP32/Tutorials/Arduino-Tutorials/13-1",
            "ESP32/Tutorials/Arduino-Tutorials/13-2",
            "ESP32/Tutorials/Arduino-Tutorials/13-3",
            "ESP32/Tutorials/Arduino-Tutorials/13-4",
            "ESP32/Tutorials/Arduino-Tutorials/13-5",
            "ESP32/Tutorials/Arduino-Tutorials/13-6",
          ],
        },
      ],
    },
        {
      type: "category",
      label: "ESP-IDF Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/ESP-IDF-Tutorials/ESP32-ESP-IDF-Tutorial-Introduction",
      },
      items: [
        "ESP32/Tutorials/ESP-IDF-Tutorials/1",
        "ESP32/Tutorials/ESP-IDF-Tutorials/2",
        "ESP32/Tutorials/ESP-IDF-Tutorials/3",
        "ESP32/Tutorials/ESP-IDF-Tutorials/4",
        "ESP32/Tutorials/ESP-IDF-Tutorials/5",
        "ESP32/Tutorials/ESP-IDF-Tutorials/6",
        {
          type: "category",
          label: "Section 7 Peripheral",
          link: { type: "doc", id: "ESP32/Tutorials/ESP-IDF-Tutorials/7" },
          items: [
            "ESP32/Tutorials/ESP-IDF-Tutorials/7-1",
            "ESP32/Tutorials/ESP-IDF-Tutorials/7-2",
            "ESP32/Tutorials/ESP-IDF-Tutorials/7-3",
          ],
        },
        "ESP32/Tutorials/ESP-IDF-Tutorials/8",
        "ESP32/Tutorials/ESP-IDF-Tutorials/9",
      ],
    },
    {
      type: "category",
      label: "MicroPython Tutorials",
      link: {
        type: "doc",
        id: "ESP32/Tutorials/MicroPython-Tutorials/ESP32-MicroPython-Tutorial-Introduction",
      },
      items: [
        "ESP32/Tutorials/MicroPython-Tutorials/1",
        "ESP32/Tutorials/MicroPython-Tutorials/2",
        "ESP32/Tutorials/MicroPython-Tutorials/3",
        "ESP32/Tutorials/MicroPython-Tutorials/4",
        "ESP32/Tutorials/MicroPython-Tutorials/5",
        "ESP32/Tutorials/MicroPython-Tutorials/6",
        "ESP32/Tutorials/MicroPython-Tutorials/7",
        "ESP32/Tutorials/MicroPython-Tutorials/8",
        "ESP32/Tutorials/MicroPython-Tutorials/9",
        "ESP32/Tutorials/MicroPython-Tutorials/10",
        "ESP32/Tutorials/MicroPython-Tutorials/11",
        {
          type: "category",
          label: "Section 12 Comprehensive Projects",
          link: { type: "doc", id: "ESP32/Tutorials/MicroPython-Tutorials/12" },
          items: [
            "ESP32/Tutorials/MicroPython-Tutorials/12-1",
            "ESP32/Tutorials/MicroPython-Tutorials/12-2",
            "ESP32/Tutorials/MicroPython-Tutorials/12-3",
            "ESP32/Tutorials/MicroPython-Tutorials/12-4",
            "ESP32/Tutorials/MicroPython-Tutorials/12-5",
            "ESP32/Tutorials/MicroPython-Tutorials/12-6",
          ],
        },
      ],
    },
  ],
  gmslboardSiderbar: [{ type: "autogenerated", dirName: "GMSL/GMSL-Deser-Board" }],
  //gmslcameraSiderbar: [{ type: "autogenerated", dirName: "GMSL/GMSL-Camera" }],
  esp32s3Sidebar: [{ type: "autogenerated", dirName: "ESP32/ESP32-S3" }],
  esp32p4Sidebar: [{ type: "autogenerated", dirName: "ESP32/ESP32-P4" }],
  esp32c3Sidebar: [{ type: "autogenerated", dirName: "ESP32/ESP32-C3" }],
  esp32c6Sidebar: [{ type: "autogenerated", dirName: "ESP32/ESP32-C6" }],
};

export default sidebars;
